from flask import Blueprint
routes = Blueprint('routes', __name__)
from .models import *
from .passangers import *
from .patients import *
from .predictions import *
from .tablesize import *
from .trainings import *
from .trainings_configurations import *
from .validations import *