version: '3.7'
services:
  iris:
    build:
      context: ./iris
    volumes:
      - ./iris:/tmp/iris
    command: -a 'sh /opt/irisapp/start.sh'
    ports:
    - 52775:52773
    - 8081:8080
    - 51776:1972
  angular:
    build:
      context: ./angular
    ports:
      - 8080:80